### ISSUE TITLE
i2c-tools 在 RT-Thread studio无法使用命令

### ISSUE THREAD

**Issue by qiaowei361** [wuhanstudio/rt-i2c-tools#2]
![image](https://user-images.githubusercontent.com/15102543/90112928-38b40e80-dd83-11ea-9136-be9bd32a02eb.png)

当输入命令如下时：

![image](https://user-images.githubusercontent.com/15102543/90113076-6731e980-dd83-11ea-8501-64fb42025bf4.png)

**Comment by wuhanstudio** [comment]
你好，最近刚刚入学之前没注意，这个是 RT-Thread 现在没有默认选中 CPP 造成的，所有源码有 C++ 的项目都受到影响了。

我已经提 PR 修复了：

https://github.com/RT-Thread/packages/pull/793
